using Sfs2X.Entities.Data;

namespace Sfs2X.Entities.Invitation
{
	/// <summary>
	/// The Invitation interface defines all the methods and properties that an object representing an invitation entity exposes.
	/// </summary>
	///
	/// <remarks>
	/// In the SmartFoxServer 2X client API this interface is implemented by the <see cref="T:Sfs2X.Entities.Invitation.SFSInvitation" /> class. Read the class description for additional informations.
	/// </remarks>
	///
	/// <seealso cref="T:Sfs2X.Entities.Invitation.SFSInvitation" />
	public interface Invitation
	{
		/// <summary>
		/// Indicates the id of this invitation.
		/// </summary>
		///
		/// <remarks>
		/// It is generated by the server when the invitation is sent.
		/// <para />
		/// <b>NOTE</b>: setting the id property manually has no effect on the server and can disrupt the API functioning.
		/// </remarks>
		int Id { get; set; }

		/// <summary>
		/// Returns the User object corresponding to the user who sent the invitation.
		/// </summary>
		User Inviter { get; }

		/// <summary>
		/// Returns the User object corresponding to the user who received the invitation.
		/// </summary>
		User Invitee { get; }

		/// <summary>
		/// Returns the number of seconds available to the invitee to reply to the invitation, after which the invitation expires.
		/// </summary>
		int SecondsForAnswer { get; }

		/// <summary>
		/// Returns an instance of SFSObject containing a custom set of parameters.
		/// </summary>
		///
		/// <remarks>
		/// This usually stores invitation details, like a message to the invitee and any other relevant data.
		/// </remarks>
		ISFSObject Params { get; }
	}
}
